-- Run in Snowflake (worksheet or snowsql) against your INFLECT database/schema.
-- Adds fundamentals fields for full JSON pipeline + extra keys from data/fundamentals/*.json

ALTER TABLE FUNDAMENTALS ADD COLUMN IF NOT EXISTS SECTOR VARCHAR(100);
ALTER TABLE FUNDAMENTALS ADD COLUMN IF NOT EXISTS INDUSTRY VARCHAR(100);
ALTER TABLE FUNDAMENTALS ADD COLUMN IF NOT EXISTS COMPANY_NAME VARCHAR(200);
ALTER TABLE FUNDAMENTALS ADD COLUMN IF NOT EXISTS EMPLOYEES INTEGER;
ALTER TABLE FUNDAMENTALS ADD COLUMN IF NOT EXISTS EBITDA FLOAT;
ALTER TABLE FUNDAMENTALS ADD COLUMN IF NOT EXISTS EBITDA_MARGINS FLOAT;
ALTER TABLE FUNDAMENTALS ADD COLUMN IF NOT EXISTS OPERATING_MARGINS FLOAT;
ALTER TABLE FUNDAMENTALS ADD COLUMN IF NOT EXISTS PEG_RATIO FLOAT;
ALTER TABLE FUNDAMENTALS ADD COLUMN IF NOT EXISTS PRICE_TO_BOOK FLOAT;
ALTER TABLE FUNDAMENTALS ADD COLUMN IF NOT EXISTS PRICE_TO_SALES FLOAT;
ALTER TABLE FUNDAMENTALS ADD COLUMN IF NOT EXISTS ROA FLOAT;
ALTER TABLE FUNDAMENTALS ADD COLUMN IF NOT EXISTS CURRENT_RATIO FLOAT;
ALTER TABLE FUNDAMENTALS ADD COLUMN IF NOT EXISTS TOTAL_CASH FLOAT;
ALTER TABLE FUNDAMENTALS ADD COLUMN IF NOT EXISTS TOTAL_DEBT FLOAT;
ALTER TABLE FUNDAMENTALS ADD COLUMN IF NOT EXISTS REVENUE_GROWTH FLOAT;
ALTER TABLE FUNDAMENTALS ADD COLUMN IF NOT EXISTS WEBSITE VARCHAR(200);
ALTER TABLE FUNDAMENTALS ADD COLUMN IF NOT EXISTS CEO VARCHAR(200);

-- JSON keys not covered above (same table as user mapping)
ALTER TABLE FUNDAMENTALS ADD COLUMN IF NOT EXISTS EPS_FORWARD FLOAT;
ALTER TABLE FUNDAMENTALS ADD COLUMN IF NOT EXISTS DESCRIPTION VARCHAR(16777216);
ALTER TABLE FUNDAMENTALS ADD COLUMN IF NOT EXISTS HIGH_52W FLOAT;
ALTER TABLE FUNDAMENTALS ADD COLUMN IF NOT EXISTS LOW_52W FLOAT;
ALTER TABLE FUNDAMENTALS ADD COLUMN IF NOT EXISTS AVG_VOLUME FLOAT;

-- News pipeline (upload_market_data inserts SENTIMENT = 0 placeholder)
ALTER TABLE NEWS ADD COLUMN IF NOT EXISTS SENTIMENT FLOAT;
